export const HANDLE_UPLOAD_IMAGE_BEGIN = "HANDLE_UPLOAD_IMAGE_BEGIN";
export const HANDLE_UPLOAD_IMAGE_SUCCESS = "HANDLE_UPLOAD_IMAGE_SUCCESS";
export const HANDLE_UPLOAD_IMAGE_FAILURE = "HANDLE_UPLOAD_IMAGE_FAILURE";

export const HANDLE_SUBMIT_IMAGE_BEGIN = "HANDLE_SUBMIT_IMAGE_BEGIN";
export const HANDLE_SUBMIT_IMAGE_SUCCESS = "HANDLE_SUBMIT_IMAGE_SUCCESS";
export const HANDLE_SUBMIT_IMAGE_FAILURE = "HANDLE_SUBMIT_IMAGE_FAILURE";

export const HANDLE_CLEAR_STATE = "HANDLE_CLEAR_STATE";
